version: '3.9'

services:
  db:
    container_name: aula-pos-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
       - "/home/allan/Projeto_Ubuntu/Aula_Banco_de_dados/docker_banco_pos/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql"
       - "/home/allan/Projeto_Ubuntu/Aula_Banco_de_dados/docker_banco_pos/init-db/init-permissions.sql:/docker-entrypoint-initdb.d/init-permissions.sql"
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: aula_pos_banco_de_dados
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - aula-pos-network
  adminer: # Adicionar o serviço Adminer
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080" # Mapear a porta 8081 do host para a porta 8080 do container do Adminer
    networks:
      - aula-pos-network # Conectar à rede aula-pos-network
networks:
  aula-pos-network:
    driver: bridge